<?php

return [
    'name' => 'Novocib',
    'logo' => 'img/logo.png',
    'legal_form' => 'SAS',
    'share_capital' => '10 000',
    'street' => 'Halle a Maree, Quai Jean Voisin',
    'city' => 'Boulogne-sur-Mer',
    'zip' => '62200',
    'country' => 'France',
    'siren' => '482 379 377',
    'siret' => '482 379 377 00012',
    'vat_number' => 'FR90482379377',
    'phone' => '+33 3 21 99 00 00',
    'email' => 'lbalakireva@novocib.com',
    'website' => 'https://novocib.com',
    'default_currency' => 'EUR',
    'default_currency_symbol' => '€',
    'default_vat_rate' => 0,
    'default_invoice_due_days' => 30,
    'default_quote_valid_days' => 30,
    'default_payment_method' => 'Bank Transfer (Wire)',
    'late_payment_rate' => 4.5,
    'late_payment_flat_fee' => 40,
    'vat_mention' => 'VAT not applicable - export outside the European Union (Article 259 of the French Tax Code)',
    'late_payment_text' => 'Late payment penalties apply from the due date.',
    'late_payment_fee_text' => 'A fixed recovery fee may also apply.',
    'terms_text' => 'Payment is due according to the terms listed on the document.',
];
